=== citrouille86/jaxb_json/src/main/resources/pizza_order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ppp="http://www.pizza.com" targetNamespace="http://www.pizza.com" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.00">
	<!-- Import the Namespaces required -->
	<xs:complexType name="CustomerType">
		<xs:sequence>
			<xs:element name="name" type="ppp:NameType"/>
			<xs:element name="phone" type="ppp:PhoneNumberType"/>
			<xs:element name="address" type="ppp:AddressType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NameType">
		<xs:sequence>
			<xs:element name="firstName" type="ppp:FirstNameType"/>
			<xs:element name="lastName" type="ppp:LastNameType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="FirstNameType">
		<xs:annotation>
			<xs:documentation>The Customer's first name</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:maxLength value="16"/>
			<xs:pattern value=".{1,16}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LastNameType">
		<xs:annotation>
			<xs:documentation>The Customer's surname</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value=".{1,48}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AddressType">
		<xs:sequence>
			<xs:element name="houseNumber" type="ppp:HouseNumberType"/>
			<xs:element name="street" type="ppp:AddressLineType"/>
			<xs:element name="town" type="ppp:AddressLineType" minOccurs="0"/>
			<xs:element name="area" type="ppp:AddressLineType" minOccurs="0"/>
			<xs:element name="postCode" type="ppp:PostCodeType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="HouseNumberType">
		<xs:annotation>
			<xs:documentation>The house number</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:nonNegativeInteger"/>
	</xs:simpleType>
	<xs:simpleType name="AddressLineType">
		<xs:annotation>
			<xs:documentation>A line of an address</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value=".{1,100}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PhoneNumberType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="18"/>
			<xs:pattern value=".{1,18}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PostCodeType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- The Root Node -->
	<xs:element name="PizzaOrder">
		<xs:annotation>
			<xs:documentation>A wrapper around the customer and the pizza order</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="orderID" type="ppp:CorrelationIdentifierType"/>
				<xs:element name="date" type="ppp:DateType"/>
				<xs:element name="time" type="ppp:TimeType"/>
				<xs:element name="Customer" type="ppp:CustomerType"/>
				<xs:element ref="ppp:pizzas"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- The Pizza Order-->
	<xs:element name="pizzas">
		<xs:annotation>
			<xs:documentation>This is a list of pizzas ordered by the customer</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pizza" type="ppp:PizzaType"  minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="PizzaType">
		<xs:sequence>
			<xs:element name="name" type="ppp:PizzaNameType">
				<xs:annotation>
					<xs:documentation>The type of pizza on the menu</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="base" type="ppp:BaseType">
				<xs:annotation>
					<xs:documentation>type of base</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="quantity" type="ppp:QuantityType">
				<xs:annotation>
					<xs:documentation>quantity of pizzas</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="PizzaNameType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Margherita">
				<xs:annotation>
					<xs:documentation>Plain and Simple</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Marinara">
				<xs:annotation>
					<xs:documentation>Garlic Pizza...</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Prosciutto e Funghi">
				<xs:annotation>
					<xs:documentation>Ham and Musheroom</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Capricciosa">
				<xs:annotation>
					<xs:documentation>with an egg</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BaseType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="thin">
				<xs:annotation>
					<xs:documentation>thin base traditional</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="thick">
				<xs:annotation>
					<xs:documentation>Thick base</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="QuantityType">
		<xs:restriction base="xs:nonNegativeInteger"/>
	</xs:simpleType>
	<xs:simpleType name="CorrelationIdentifierType">
		<xs:restriction base="xs:token">
			<xs:maxLength value="44"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateType">
		<xs:annotation>
			<xs:documentation>The date is in the Common Era (minus sign in years is not permitted)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimeType">
		<xs:annotation>
			<xs:documentation>The time zone although not included UTC is implied</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:time">
			<xs:pattern value="\d{2}:\d{2}:\d{2}(\.\d+)?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== citrouille86/jaxb_json/src/xml/pizza_order2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ppp:PizzaOrder xmlns:ppp="http://www.pizza.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pizza.com pizza_order.xsd ">
  <ppp:orderID>commande2</ppp:orderID>
  <ppp:date>2018-01-01</ppp:date>
  <ppp:time>12:00:00</ppp:time>
  <ppp:Customer>
    <ppp:name>
      <ppp:firstName>Lucky</ppp:firstName>
      <ppp:lastName>Luke</ppp:lastName>
    </ppp:name>
    <ppp:phone>0123456789</ppp:phone>
    <ppp:address>
      <ppp:houseNumber>12</ppp:houseNumber>
      <ppp:street>rue des oiseaux</ppp:street>
      <ppp:postCode>37000</ppp:postCode>
    </ppp:address>
  </ppp:Customer>
  <ppp:pizzas>
    <ppp:pizza>
      <ppp:name>Prosciutto e Funghi</ppp:name>
      <ppp:base>thick</ppp:base>
      <ppp:quantity>1</ppp:quantity>
    </ppp:pizza>
    <ppp:pizza>
      <ppp:name>Capricciosa</ppp:name>
      <ppp:base>thin</ppp:base>
      <ppp:quantity>1</ppp:quantity>
    </ppp:pizza>
  </ppp:pizzas>
</ppp:PizzaOrder>

=== citrouille86/jaxb_json/src/xml/pizza_order.xml
<?xml version="1.0" encoding="UTF-8"?>
<ppp:PizzaOrder xmlns:ppp="http://www.pizza.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pizza.com pizza_order.xsd ">
  <ppp:orderID>commande1</ppp:orderID>
  <ppp:date>2018-02-01</ppp:date>
  <ppp:time>12:30:00</ppp:time>
  <ppp:Customer>
    <ppp:name>
      <ppp:firstName>Bob</ppp:firstName>
      <ppp:lastName>Morane</ppp:lastName>
    </ppp:name>
    <ppp:phone>0666666666</ppp:phone>
    <ppp:address>
      <ppp:houseNumber>666</ppp:houseNumber>
      <ppp:street>rue des martyrs</ppp:street>
      <ppp:postCode>37400</ppp:postCode>
    </ppp:address>
  </ppp:Customer>
  <ppp:pizzas>
    <ppp:pizza>
      <ppp:name>Margherita</ppp:name>
      <ppp:base>thin</ppp:base>
      <ppp:quantity>2</ppp:quantity>
    </ppp:pizza>
  </ppp:pizzas>
  <ppp:pizzas>
    <ppp:pizza>
      <ppp:name>Marinara</ppp:name>
      <ppp:base>thin</ppp:base>
      <ppp:quantity>1</ppp:quantity>
    </ppp:pizza>
  </ppp:pizzas>
</ppp:PizzaOrder>

=== citrouille86/jaxb_json/src/xml/pizza_order66.xml
<?xml version="1.0" encoding="UTF-8"?>
<ppp:PizzaOrder xmlns:ppp="http://www.pizza.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pizza.com ../main/resources/pizza_order.xsd ">
  <ppp:orderID>token</ppp:orderID>
  <ppp:date>2001-01-01</ppp:date>
  <ppp:time>12:00:00</ppp:time>
  <ppp:Customer>
    <ppp:name>
      <ppp:firstName>token</ppp:firstName>
      <ppp:lastName>token</ppp:lastName>
    </ppp:name>
    <ppp:phone>token</ppp:phone>
    <ppp:address>
      <ppp:houseNumber>0</ppp:houseNumber>
      <ppp:street>token</ppp:street>
      <ppp:postCode>token</ppp:postCode>
    </ppp:address>
  </ppp:Customer>
  <ppp:pizzas>
    <ppp:pizza>
      <ppp:name>Margherita</ppp:name>
      <ppp:base>thin</ppp:base>
      <ppp:quantity>0</ppp:quantity>
    </ppp:pizza>
  </ppp:pizzas>
</ppp:PizzaOrder>
